version: '3.8'
services:
  gradlebackendapplication:
    build: .
    image: gradlebackendapplication:latest
    ports:
      - "8081:8080"
    networks:
      - backend
networks:
  backend:
    external: true