version: '3.8'
services:
  gradlebackendapplication:
    build: .
    image: gradlebackendapplication:latest
    network_mode: host
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:

