
spring:
  datasource:
    url: jdbc:postgresql://192.168.178.81:5432/database
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true