
spring:
  application:
    name: ProductService
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://192.168.178.32:5432/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Weather API Configuration
weather:
  api:
    url: https://api.openweathermap.org/data/2.5/weather
    key: bc434c2a45290f97cb9d123eb8b45879
  default:
    location: Trudering
server:
  port: 8060

# Logging Configuration
logging:
  level:
    root: INFO
    com.petziferum.gradlebackend: DEBUG
